//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsciiAnimation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AsciiAnimation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                      
        ///     |`&quot;-. _________________ .-&quot;&apos;|     
        ///     |     |- a:f -        |     |     
        ///     |     |               |  _. |     
        ///     |     |          .--. | | | |     
        ///     |     |          |  | | | | |     
        ///     |     |__________|  |_|  &quot;&apos; |     
        ///     |.--&apos;                   `--.|     
        ///
        ///
        ///Q                                       
        ///     |`&quot;-. _________________ .-&quot;&apos;|     
        ///     |     |- a:f -        |     |     
        ///     |     |               |  _. |     
        ///     |     |      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ComputerAnger {
            get {
                return ResourceManager.GetString("ComputerAnger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  o  
        /// /#\ 
        /// _|_ 
        ///Z
        /// \o/ 
        ///  #  
        ///_/ \_
        ///.
        /// </summary>
        internal static string JumpingJacks {
            get {
                return ResourceManager.GetString("JumpingJacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///LOL
        ///   O
        ///    L
        ///     O
        ///      L         LOL   LOL
        ///       O       O   O O   O
        ///        L     L     L     L
        ///         O   O       O   O     LOL
        ///          LOL         LOL     L
        ///                         O   O
        ///                          LOL
        ///A
        ///)
        ///LOL
        ///   O
        ///    L
        ///     O
        ///      L         LOL   LOL
        ///       O       O   O O   O
        ///        L     L     L     L
        ///         O   O       O   O     LOL
        ///          LOL         LOL     L
        ///                         O   O
        ///                          LOL
        ///A
        ///_)
        ///LOL
        ///   O
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Lollercoaster {
            get {
                return ResourceManager.GetString("Lollercoaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                     
        ///                    
        ///                    
        ///                    
        ///                    
        ///                    
        ///                    
        ///_____________ o ____
        ///~ ~ ~ ~ ~ ~ ~&lt; &gt;~ ~ 
        ///              |     
        ///
        ///
        ///Z                    
        ///                    
        ///                    
        ///                    
        ///                    
        ///                    
        ///                    
        ///_____________ o ___&lt;
        ///~ ~ ~ ~ ~ ~ ~&lt; &gt;~ ~ 
        ///              |     
        ///
        ///
        ///Z                    
        ///                    
        ///                   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Train {
            get {
                return ResourceManager.GetString("Train", resourceCulture);
            }
        }
    }
}
