// Alex Fuhr

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MadLib
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.BackgroundColor = ConsoleColor.Yellow;
            Console.Clear();
            const ConsoleColor PROMPT_COLOR = ConsoleColor.Red;
            const ConsoleColor INPUT_COLOR = ConsoleColor.Cyan;
            const ConsoleColor RESULT_COLOR = ConsoleColor.DarkBlue;
            const ConsoleColor STORY_COLOR = ConsoleColor.Blue;

            Console.Title = "The Adventures of the Alice Chicken";

            Console.ForegroundColor = STORY_COLOR;
            Console.WriteLine("Today, you will help create the story of a famous chicken's life.");
            Console.WriteLine("Fill in the prompts to continue.");
            Console.WriteLine("");
            Console.ForegroundColor = PROMPT_COLOR;
            Console.Write("Adjective  ");
            Console.ForegroundColor = INPUT_COLOR;
            String adj1 = Console.ReadLine();
            Console.ForegroundColor = PROMPT_COLOR;
            Console.Write("Noun (plural)  ");
            Console.ForegroundColor = INPUT_COLOR;
            String pn1 = Console.ReadLine();
            Console.ForegroundColor = PROMPT_COLOR;
            Console.Write("Noun (singular)  ");
            Console.ForegroundColor = INPUT_COLOR;
            String sn1 = Console.ReadLine();
            Console.ForegroundColor = PROMPT_COLOR;
            Console.Write("Verb (present)  ");
            Console.ForegroundColor = INPUT_COLOR;
            String prv1 = Console.ReadLine();
            Console.ForegroundColor = PROMPT_COLOR;
            Console.Write("Adjective  ");
            Console.ForegroundColor = INPUT_COLOR;
            String adj2 = Console.ReadLine();
            Console.ForegroundColor = PROMPT_COLOR;
            Console.Write("Noun (singular, person or thing)  ");
            Console.ForegroundColor = INPUT_COLOR;
            String sn2 = Console.ReadLine();
            Console.ForegroundColor = PROMPT_COLOR;
            Console.Write("Noun (singular)  ");
            Console.ForegroundColor = INPUT_COLOR;
            String sn3 = Console.ReadLine();
            Console.ForegroundColor = PROMPT_COLOR;
            Console.Write("Noun (plural, person or thing  ");
            Console.ForegroundColor = INPUT_COLOR;
            String pn2 = Console.ReadLine();
            Console.ForegroundColor = PROMPT_COLOR;
            Console.Write("Verb (present)  ");
            Console.ForegroundColor = INPUT_COLOR;
            String prv2 = Console.ReadLine();
            Console.ForegroundColor = PROMPT_COLOR;
            Console.Write("Adjective  ");
            Console.ForegroundColor = INPUT_COLOR;
            String adj3 = Console.ReadLine();
            Console.ForegroundColor = PROMPT_COLOR;
            Console.Write("Verb (present)  ");
            Console.ForegroundColor = INPUT_COLOR;
            String prv3 = Console.ReadLine();
            Console.ForegroundColor = PROMPT_COLOR;
            Console.Write("Direction  ");
            Console.ForegroundColor = INPUT_COLOR;
            String d = Console.ReadLine();
            Console.ForegroundColor = PROMPT_COLOR;
            Console.Write("Number  ");
            Console.ForegroundColor = INPUT_COLOR;
            String n = Console.ReadLine();
            Console.ForegroundColor = PROMPT_COLOR;
            Console.Write("Unit of Measurement (must agree w/ number)  ");
            Console.ForegroundColor = INPUT_COLOR;
            String m = Console.ReadLine();
            Console.ForegroundColor = PROMPT_COLOR;
            Console.Write("Interjection (capitalized)  ");
            Console.ForegroundColor = INPUT_COLOR;
            String intj1 = Console.ReadLine();
            Console.ForegroundColor = PROMPT_COLOR;
            Console.Write("Noun (singular)  ");
            Console.ForegroundColor = INPUT_COLOR;
            String sn4 = Console.ReadLine();
            Console.ForegroundColor = PROMPT_COLOR;
            Console.Write("Noun (plural)  ");
            Console.ForegroundColor = INPUT_COLOR;
            String pn3 = Console.ReadLine();
            Console.ForegroundColor = PROMPT_COLOR;
            Console.Write("Adverb  ");
            Console.ForegroundColor = INPUT_COLOR;
            String adv = Console.ReadLine();
            Console.ForegroundColor = PROMPT_COLOR;
            Console.Write("Noun (singular, person or thing  ");
            Console.ForegroundColor = INPUT_COLOR;
            String sn5 = Console.ReadLine();
            Console.ForegroundColor = PROMPT_COLOR;
            Console.Write("Noun (singular)  ");
            Console.ForegroundColor = INPUT_COLOR;
            String sn6 = Console.ReadLine();
            Console.ForegroundColor = PROMPT_COLOR;
            Console.Write("Verb (present)  ");
            Console.ForegroundColor = INPUT_COLOR;
            String prv4 = Console.ReadLine();
            Console.ForegroundColor = PROMPT_COLOR;
            Console.Write("Past Participle  ");
            Console.ForegroundColor = INPUT_COLOR;
            String ppart = Console.ReadLine();
            Console.ForegroundColor = PROMPT_COLOR;
            Console.Write("Adjective  ");
            Console.ForegroundColor = INPUT_COLOR;
            String adj4 = Console.ReadLine();
            Console.ForegroundColor = PROMPT_COLOR;
            Console.Write("Noun (singular, person or thing  ");
            Console.ForegroundColor = INPUT_COLOR;
            String sn7 = Console.ReadLine();
            Console.ForegroundColor = PROMPT_COLOR;
            Console.Write("Interjection (capitalized)  ");
            Console.ForegroundColor = INPUT_COLOR;
            String intj2 = Console.ReadLine();
            Console.ForegroundColor = PROMPT_COLOR;
            Console.Write("Place  ");
            Console.ForegroundColor = INPUT_COLOR;
            String place = Console.ReadLine();
            Console.WriteLine();

            Console.ForegroundColor = STORY_COLOR;
            Console.Write("      Once, there was a(n) ");
            Console.ForegroundColor = RESULT_COLOR;
            Console.Write(adj1);
            Console.ForegroundColor = STORY_COLOR;
            Console.Write(" chicken who decided that he was just not earning his ");
            Console.ForegroundColor = RESULT_COLOR;
            Console.Write(pn1);
            Console.ForegroundColor = STORY_COLOR;
            Console.Write(". He needed a job. The ");
            Console.ForegroundColor = RESULT_COLOR;
            Console.Write(sn1);
            Console.ForegroundColor = STORY_COLOR;
            Console.Write(" was, where should he ");
            Console.ForegroundColor = RESULT_COLOR;
            Console.Write(prv1);
            Console.ForegroundColor = STORY_COLOR;
            Console.Write(" this job? It was then that he saw a(n) ");
            Console.ForegroundColor = RESULT_COLOR;
            Console.Write(adj2);
            Console.ForegroundColor = STORY_COLOR;
            Console.Write(" scene with a snow");
            Console.ForegroundColor = RESULT_COLOR;
            Console.Write(sn2);
            Console.ForegroundColor = STORY_COLOR;
            Console.Write(" being rejected by a snowwoman. Nearby a giant ");
            Console.ForegroundColor = RESULT_COLOR;
            Console.Write(sn3);
            Console.ForegroundColor = STORY_COLOR;
            Console.Write(" stood with the name Alice Industries. It appeared to be an educational faciliy, where young ");
            Console.ForegroundColor = RESULT_COLOR;
            Console.Write(pn2);
            Console.ForegroundColor = STORY_COLOR;
            Console.Write(" learned how to ");
            Console.ForegroundColor = RESULT_COLOR;
            Console.Write(prv2);
            Console.ForegroundColor = STORY_COLOR;
            Console.Write(" instructions to real-life objects. It was a(n) ");
            Console.ForegroundColor = RESULT_COLOR;
            Console.Write(adj3);
            Console.ForegroundColor = STORY_COLOR;
            Console.Write(" place for a job. Excitedly the chicken applied, and the only instruction given was ");
            Console.ForegroundColor = RESULT_COLOR;
            Console.Write(prv3);
            Console.ForegroundColor = STORY_COLOR;
            Console.Write(" ");
            Console.ForegroundColor = RESULT_COLOR;
            Console.Write(d);
            Console.ForegroundColor = STORY_COLOR;
            Console.Write(" ");
            Console.ForegroundColor = RESULT_COLOR;
            Console.Write(n);
            Console.ForegroundColor = STORY_COLOR;
            Console.Write(" ");
            Console.ForegroundColor = RESULT_COLOR;
            Console.Write(m);
            Console.ForegroundColor = STORY_COLOR;
            Console.Write(". ");
            Console.ForegroundColor = RESULT_COLOR;
            Console.Write(intj1);
            Console.ForegroundColor = STORY_COLOR;
            Console.Write("! The administrators remarked. You could be our top ");
            Console.ForegroundColor = RESULT_COLOR;
            Console.Write(sn4);
            Console.ForegroundColor = STORY_COLOR;
            Console.WriteLine("!");
            Console.WriteLine("");
            Console.Write("      The chicken then went through many ");
            Console.ForegroundColor = RESULT_COLOR;
            Console.Write(pn3);
            Console.ForegroundColor = STORY_COLOR;
            Console.Write(" on which it performed ");
            Console.ForegroundColor = RESULT_COLOR;
            Console.Write(adv);
            Console.ForegroundColor = STORY_COLOR;
            Console.Write(". Then, however, one Alice ");
            Console.ForegroundColor = RESULT_COLOR;
            Console.Write(sn5);
            Console.ForegroundColor = STORY_COLOR;
            Console.Write(" used the chicken for his graduation test. He had to construct a shooting ");
            Console.ForegroundColor = RESULT_COLOR;
            Console.Write(sn6);
            Console.ForegroundColor = STORY_COLOR;
            Console.Write(" on which the chicken would ");
            Console.ForegroundColor = RESULT_COLOR;
            Console.Write(prv4);
            Console.ForegroundColor = STORY_COLOR;
            Console.Write(" to avoid being ");
            Console.ForegroundColor = RESULT_COLOR;
            Console.Write(ppart);
            Console.ForegroundColor = STORY_COLOR;
            Console.Write(". However, the student input ");
            Console.ForegroundColor = RESULT_COLOR;
            Console.Write(adj4);
            Console.ForegroundColor = STORY_COLOR;
            Console.Write(" movements for the chicken, and easily shot a rock-solid ");
            Console.ForegroundColor = RESULT_COLOR;
            Console.Write(sn7);
            Console.ForegroundColor = STORY_COLOR;
            Console.Write(" into the chicken. ");
            Console.ForegroundColor = RESULT_COLOR;
            Console.Write(intj2);
            Console.ForegroundColor = STORY_COLOR;
            Console.Write("! The chicken exclaimed. I want to go back to ");
            Console.ForegroundColor = RESULT_COLOR;
            Console.Write(place);
            Console.ForegroundColor = STORY_COLOR;
            Console.WriteLine(".");
        }
    }
}
